### ISSUE TITLE
Could you please make the endpoint /prometheus configurable?

### ISSUE THREAD

**Issue by diegopereiraeng** [MaksymDolgykh/dropwizard-micrometer#19]

**Comment by MaksymDolgykh** [comment]
Hi @diegopereiraeng! This bundle is now configurable, so that you can customise prometheus endpoint. You will need to **upgrade to version 3.0.0** and **adjust app configuration class**. Please find more details in the readme [here]( https://github.com/MaksymDolgykh/dropwizard-micrometer/tree/21380c04e518263d2c3918d7c84b47ce3971ccad#add-the-bundle-to-your-application)
If you need any further assistance please let me know.
