### ISSUE TITLE
Prometheus Query Examples

### ISSUE THREAD

**Issue by diegopereiraeng** [MaksymDolgykh/dropwizard-micrometer#20]
Hi, I'm not an advanced prometheus user, and it should be great some example queries how to get response time from the metrics, i'm struggling with this, thank you

**Comment by MaksymDolgykh** [comment]
Hello, I've an example dropwizard app which exposes prometheus metrics with this package
https://github.com/MaksymDolgykh/dropwizard-example-app

There are a few grafana dashboards in that stack to demonstrate metrics provided by 
[dropwizard-micrometer](https://github.com/MaksymDolgykh/dropwizard-micrometer) package.

You can spin up that example stack with docker-compose and see how metrics look like in dashboards. The dashboards itself are json files (so that example queries are human readable).

If you are interested in more examples please let me know.

**Comment by diegopereiraeng** [comment]
Thank you very much for the help, loved the examples =D
